### ISSUE TITLE
Is this going to replace WordPress site?

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/news-o-o#1]
I am planing to apply Chameleon theme to news.o.o website. I saw it still use WordPress. But here the code is static website generator.

If it will replace WordPress, I can start to adopt theme for it.

**Comment by hellcp** [comment]
Yes, that's correct. We are getting rid of wordpress in general. Lizards-o-o is dying, this is getting replaced with jekyll

**Comment by vinzv** [comment]
Issue resolved, closing.
