### ISSUE TITLE
full feed vs. shortened feed

### ISSUE THREAD

**Issue by cboltz** [openSUSE/news-o-o#10]
Since an hour, the RSS feed gets shortened to 50 words, while it historically was a full feed with the complete article.

I'd prefer to keep the full feed as feed.xml (so that I can read everything in Akregator), but maybe you could add an alternative, shortened feed (shortfeed.xml?) for people who prefer that.

**Comment by hellcp** [comment]
That was why opensuse.org had broken feeds, I looked at rss spec and couldn't find the equivalent of description/content that atom feeds have, but I might be blind

**Comment by hellcp** [comment]
Wordpress adds <content:encoded>, which while out of spec, sounds like a good way to do it

**Comment by hellcp** [comment]
It's xmlns:content="http://purl.org/rss/1.0/modules/content/" extension btw
