### ISSUE TITLE
Typo in Entering Leap Bugs Gains New Clarity article

### ISSUE THREAD

**Issue by victorhck** [openSUSE/news-o-o#115]
Hello.

In 2nd parragraph you can read:
> A the distribution evolved from...

Should be?

> A**s** the distribution evolved from...

I wrote a comment:
https://github.com/openSUSE/news-o-o/commit/972addccb444028459e683225072fcbb07100f5f#r69742477

BTW: I always mail to @ddemaio when I found a typo or similar in the articles, but I maybe open an issue here it's better.
Maybe can be added a tag with typo or similar...

Regards.

**Comment by ddemaio** [comment]
Thank you @victorhck I made the change. It's posting now and will take about an hour to show on news.o.o.
