### ISSUE TITLE
Image Not Responsive

### ISSUE THREAD

**Issue by cho2** [openSUSE/news-o-o#14]
Open news.o.o on mobile browser

![news-o-o](https://user-images.githubusercontent.com/6271071/75893242-14174a80-5e65-11ea-84c8-35b77a4ca811.jpg)

It should be like this

![screenshot-news opensuse org-2020 03 04-22_12_00](https://user-images.githubusercontent.com/6271071/75893322-33ae7300-5e65-11ea-83e9-607f464e1221.png)

**Comment by hellcp** [comment]
What browser is that?

**Comment by cho2** [comment]
@hellcp Google Chrome

Trying in a different browser looks good

Firefox
![news-o-o-firefox](https://user-images.githubusercontent.com/6271071/75895399-2f378980-5e68-11ea-8ff3-68eea21509c0.jpg)


Opera
![news-o-o-opera](https://user-images.githubusercontent.com/6271071/75895419-352d6a80-5e68-11ea-99af-5ed608ee354c.jpg)

**Comment by vinzv** [comment]
Can't reproduce this on Chrome 80.0.3987.132 / Realme Pro 5 phone.
