### ISSUE TITLE
Can't be used mailto tag?

### ISSUE THREAD

**Issue by victorhck** [openSUSE/news-o-o#187]
Hello!
Recently I can read in news.o.o articles that share a email address as contact. Can't be used in Jekyll some kind of `mailto` tag to make more easy to write an email to that address?
Greetings.

**Comment by hellcp** [comment]
Using the normal URL format should work `[Send me an email](mailto:hello@world.com)`

**Comment by victorhck** [comment]
I sent #188 PR to test

**Comment by victorhck** [comment]
Seems that works ok!
thanks a lot!

**Comment by ddemaio** [comment]
<hello@world.com> works with markdown as well. You can see it in https://news.opensuse.org/2023/11/22/submit-a-presentation-for-osc/

**Comment by victorhck** [comment]
Yes I saw it. I was thinking about that maybe could be also a good idea to add a subject. That way all mails from that place would be the same subject in your inbox and could be useful to you:
`[contact in my mail](mailto:supercool@mail.com?subject=volunteers oSC24)`
