### ISSUE TITLE
systemd-fde article could do with links

### ISSUE THREAD

**Issue by JohnVeness** [openSUSE/news-o-o#191]
@aplanas Thank you for the interesting article https://news.opensuse.org/2023/12/20/systemd-fde/

However, I notice it isn't very web-friendly. It contains footnote references that aren't clickable (so one would have to manually scroll down to find the reference), and the URLs within the footnotes are also not clickable (so one would have to copy and paste). Are you able to fix this?

**Comment by aplanas** [comment]
@JohnVeness yes, good point. I think https://github.com/openSUSE/news-o-o/pull/192 will fix this issue

**Comment by JohnVeness** [comment]
Thanks, looks good now :)

Can you also submit to https://github.com/kubic-project/microos-o-o/ ?

**Comment by aplanas** [comment]
Done here: https://github.com/kubic-project/microos-o-o/pull/10
