### ISSUE TITLE
large images in wp-content/uploads/2024/01

### ISSUE THREAD

**Issue by zebh** [openSUSE/news-o-o#197]
I noticed that loading news-o-o took a long time and checked it in Firefox's developer tools and found it downloaded some rather big images.

I've tracked them down to `wp-content/uploads/2024/01`. `leap.png` in particular is almost 10MB.

Seems to be a simple miss, might it be possible to replace them with more optimized images?

**Comment by ddemaio** [comment]
Thank you @zebh I resized the images
