### ISSUE TITLE
Add Mastodon share option

### ISSUE THREAD

**Issue by cboltz** [openSUSE/news-o-o#246]
We have share options for Twitter, Facebook etc. in the footer of each article.

However, a "share on Mastodon" button is missing - would be a nice addition.

**Comment by ddemaio** [comment]
Updated with button in latest commit

**Comment by hellcp** [comment]
Unhelpful implementation, if your account isn't on mastodon.social, you will be greeted with the following:
![Screenshot from 2024-07-29 19-45-32](https://github.com/user-attachments/assets/9922b5ae-0f47-4404-972b-f189d32b64ce)

**Comment by ddemaio** [comment]
function now works. I'll close this out.
