### ISSUE TITLE
Sticky navbar from jekyll-theme missing

### ISSUE THREAD

**Issue by vinzv** [openSUSE/news-o-o#39]
I fixed the sticky navbar at https://github.com/openSUSE/jekyll-theme/commit/a8be4972e581d0ce2ccf61fd09be7a5d9c42435a a while ago and thought it would be pulled in here automatically. Anyone mind having a look?

**Comment by hellcp** [comment]
You need to update the Gemfile.lock's version of the dependency

**Comment by vinzv** [comment]
Hm, that did not work:

```
Fetching https://github.com/opensuse/jekyll-theme.git
Could not find jekyll-theme-opensuse-0.2.0 in any of the sources
##[error]Process completed with exit code 7.
```

I only changed the revision at https://github.com/openSUSE/news-o-o/blob/e2ce778806b998027ab9fd3bce69529f6132ac60/Gemfile.lock#L3

**Comment by hellcp** [comment]
The version should be 0.3.0

**Comment by vinzv** [comment]
Thanks, fixed.
