### ISSUE TITLE
Expand readme to include instruction on how to contribute

### ISSUE THREAD

**Issue by hellcp** [openSUSE/news-o-o#5]
There was already a post on news-o-o for it, but it would be nice to expand the readme so people coming here will be able to familiarize themselves with the process.

**Comment by guoyunhe** [comment]
GitHub recommend a `CONTRIBUTING.md` which will show an alert before users create issues or PRs.

**Comment by hellcp** [comment]
They first need to know how to create issue or PR

**Comment by guoyunhe** [comment]
Oh, yes.

**Comment by hellcp** [comment]
Fixed, thank you
