### ISSUE TITLE
License for published content

### ISSUE THREAD

**Issue by victorhck** [openSUSE/news-o-o#9]
Hello!
Great work done!! I like it this new site.
Maybe should be added under what license is published the content in the site. (maybe a foot note, or head note)

Greetings.

**Comment by hellcp** [comment]
I agree, we should use the same license as all of the new content, @ddemaio do you remember what license you decided on with the board for the news-o-o articles?

**Comment by vinzv** [comment]
Either we didn't decide at all or I wasn't there when you did decide. Let's see what @ddemaio says.

**Comment by ddemaio** [comment]
I'm leaning toward GPLv3 @vinzv @victorhck @hellcp. I don't recall having a discussion with the board about what license to use for the new news.o.o. Jekyll is MIT, but can it can be re-licensed under other licenses. I think GPLv3 is the best fit for new.o.o. being a media source and it's more favorable b/c it protects against the Digital Millennium Copyright Act and the European Union Copyright Directive that make it a crime to write or share software that can break DRM.

**Comment by hellcp** [comment]
Sounds good to me, we just need a permission to relicense from @guoyunhe and @vinzv as the contributors, and will have to have a note about ancient posts from various authors being licensed differently, because we didn't contact them for confirmation. Alternatively we could just add a copyright field into the post frontmatter to actually make note of that. I'm not sure GPL is a good license for content though, so maybe we should consider a different license for posts themselves.

**Comment by vinzv** [comment]
> we just need a permission to relicense from @guoyunhe and @vinzv as the contributors

That's fine with me, of course.

> I'm not sure GPL is a good license for content though, so maybe we should consider a different license for posts themselves.

Looking around on the web I get the impression that for text content like in blog posts Creative Commons are the way to go for most people. GPL is not recommended there as it's made for code. The mostly mentioned alternative license for content besides CC is GFDL but imho this suites real documentation better (like our wiki does). Furthermore it requires the full license to be included which makes it hard if someone wants to use our header images solely.

Useful: https://en.wikipedia.org/wiki/Wikipedia:Comparison_of_GFDL_and_CC_BY-SA

**Comment by ddemaio** [comment]
I think we should avoid GFDL. Either CC BY or CC BY-SA would be good for the content. How do you feel about CC BY-SA? Looks like we will need to link to the license at https://creativecommons.org/licenses/

**Comment by hellcp** [comment]
Yup, I agree, I license the images intended for open sourcing as CC BY-SA too, so that works out ;)

**Comment by vinzv** [comment]
Yes, I'd choose CC as well as BY-SA. Imho pushing people towards sharing their improvements in a free way is one of our duties here, somehow.

**Comment by guoyunhe** [comment]
I am okay with any open source and CC licenses. Our wiki is licensed with GFDL https://en.opensuse.org/Terms_of_site maybe it is a historical decision.

**Comment by ddemaio** [comment]
Probably goes back to @vinzv point about GFDL being mostly for documentation @guoyunhe

**Comment by vinzv** [comment]
We can't just force relicensing the whole content back til 2007, I assume. So we only can license new and future content. But even then we should have a mechanism to show the license _per article_ to give individual authors choice and at least credit them appropriately.

**Comment by guoyunhe** [comment]
by the way, the Jekyll code is moved to https://github.com/openSUSE/jekyll-theme

so this repo is mostly for licensing the content.

we can have multiple licenses. for old content that we cannot get permission of every authors, just leave it as it was. for new content from now on, use CC license.

**Comment by hellcp** [comment]
Every post should have a `license:` frontmatter and that should be somehow displayed on the site.

**Comment by guoyunhe** [comment]
please check pr https://github.com/openSUSE/jekyll-theme/pull/8

**Comment by vinzv** [comment]
Resolved via #30
